In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

train_df=pd.read_csv('train_df_v1.tsv',sep='\t')

In [2]:
display(train_df)

SUBJECT_ID   HADM_ID  ICUSTAY_ID  \
0        18106347  24305596    30588857   
1        17195991  23542772    38319097   
2        16284044  23864737    36817845   
3        18122666  23883987    39753527   
4        18780420  28977824    32140208   
...           ...       ...         ...   
76535    15338454  29642380    37340595   
76536    18451791  28897092    32688519   
76537    12844772  26783082    37001422   
76538    14239401  21199923    35906940   
76539    16703369  27928947    36321770   

                                         FIRST_CAREUNIT  \
0          Cardiac Vascular Intensive Care Unit (CVICU)   
1                   Surgical Intensive Care Unit (SICU)   
2          Cardiac Vascular Intensive Care Unit (CVICU)   
3      Medical/Surgical Intensive Care Unit (MICU/SICU)   
4       Neuro Surgical Intensive Care Unit (Neuro SICU)   
...                                                 ...   
76535                Medical Intensive Care Unit (MICU)   
76536  Medical/Surgical Intensive Care Unit (MICU/SICU)   
76537   Neuro Surgical Intensive Care Unit (Neuro SICU)   
76538                Medical Intensive Care Unit (MICU)   
76539                                Neuro Intermediate   

                                          LAST_CAREUNIT               INTIME  \
0          Cardiac Vascular Intensive Care Unit (CVICU)  2110-01-11 10:16:06   
1                   Surgical Intensive Care Unit (SICU)  2110-01-12 00:54:00   
2          Cardiac Vascular Intensive Care Unit (CVICU)  2110-01-13 09:09:40   
3      Medical/Surgical Intensive Care Unit (MICU/SICU)  2110-01-14 07:22:00   
4       Neuro Surgical Intensive Care Unit (Neuro SICU)  2110-01-17 00:28:00   
...                                                 ...                  ...   
76535                Medical Intensive Care Unit (MICU)  2210-11-21 18:42:56   
76536  Medical/Surgical Intensive Care Unit (MICU/SICU)  2211-01-05 10:59:50   
76537   Neuro Surgical Intensive Care Unit (Neuro SICU)  2211-01-14 14:37:00   
76538                Medical Intensive Care Unit (MICU)  2211-05-01 06:59:19   
76539                                Neuro Intermediate  2211-11-09 03:33:00   

                   OUTTIME       LOS            ADMITTIME  \
0      2110-01-12 17:17:47  1.292836  2110-01-11 10:14:00   
1      2110-01-14 22:07:39  2.884479  2110-01-11 22:47:00   
2      2110-01-15 21:45:33  2.524919  2110-01-11 19:58:00   
3      2110-01-15 13:08:36  1.240694  2110-01-14 05:17:00   
4      2110-01-18 01:21:22  1.037060  2110-01-16 23:37:00   
...                    ...       ...                  ...   
76535  2210-11-23 16:03:45  1.889456  2210-11-18 21:47:00   
76536  2211-01-06 17:00:09  1.250220  2211-01-05 10:58:00   
76537  2211-01-17 15:23:45  3.032465  2211-01-14 13:14:00   
76538  2211-05-10 22:51:06  9.660961  2211-05-01 06:57:00   
76539  2211-11-11 18:34:18  2.625903  2211-11-09 02:26:00   

                 DISCHTIME            DEATHTIME     ADMISSION_TYPE  \
0      2110-01-15 17:31:00                  NaN           EW EMER.   
1      2110-01-18 10:25:00                  NaN           EW EMER.   
2      2110-01-17 16:00:00                  NaN             URGENT   
3      2110-01-16 16:34:00                  NaN           EW EMER.   
4      2110-01-22 16:07:00                  NaN           EW EMER.   
...                    ...                  ...                ...   
76535  2210-12-01 17:51:00                  NaN           EW EMER.   
76536  2211-01-07 16:30:00                  NaN       DIRECT EMER.   
76537  2211-01-17 12:34:00  2211-01-17 12:34:00           EW EMER.   
76538  2211-05-12 17:54:00                  NaN           EW EMER.   
76539  2211-11-11 18:15:00                  NaN  OBSERVATION ADMIT   

           ADMISSION_LOCATION            DISCHARGE_LOCATION INSURANCE  \
0                        PACU              HOME HEALTH CARE     Other   
1              EMERGENCY ROOM  CHRONIC/LONG TERM ACUTE CARE     Other   
2      TRANSFER FROM HOSPIT

In [31]:
# generate subject split, don't run 
# subject_ids = train_df['SUBJECT_ID'].tolist()
# print(len(subject_ids))
# subject_ids_set = set(subject_ids)
# print(len(subject_ids_set))

# subject_unique_ids = list(subject_ids_set)
# print(len(subject_unique_ids))

# from sklearn.model_selection import train_test_split

# subject_train, subject_test = train_test_split(subject_unique_ids, test_size=0.15,random_state = 42)
# print(len(subject_train))
# print(len(subject_test))

# split_subjects = []
# for subject in subject_train:
#     split_subjects.append((subject, 'train'))
# for subject in subject_test:
#     split_subjects.append((subject, 'test'))
    
# subject_df = pd.DataFrame(split_subjects, columns=['SUBJECT_ID', 'SUBJECT_LABLE'])
# display(subject_df)


# subject_df.to_csv('subject_split_df.tsv', sep='\t', index=False)

# run here
subject_df= pd.read_csv('subject_split_df.tsv', sep='\t')
display(subject_df)

train_df_split = train_df.merge(subject_df, on='SUBJECT_ID', how='left')
display(train_df_split)

SUBJECT_ID SUBJECT_LABLE
0        15146009         train
1        12100760         train
2        16128608         train
3        19258813         train
4        13884765         train
...           ...           ...
53145    15126859          test
53146    10082543          test
53147    11641327          test
53148    11117353          test
53149    16638424          test

[53150 rows x 2 columns]

SUBJECT_ID   HADM_ID  ICUSTAY_ID  \
0        18106347  24305596    30588857   
1        17195991  23542772    38319097   
2        16284044  23864737    36817845   
3        18122666  23883987    39753527   
4        18780420  28977824    32140208   
...           ...       ...         ...   
76535    15338454  29642380    37340595   
76536    18451791  28897092    32688519   
76537    12844772  26783082    37001422   
76538    14239401  21199923    35906940   
76539    16703369  27928947    36321770   

                                         FIRST_CAREUNIT  \
0          Cardiac Vascular Intensive Care Unit (CVICU)   
1                   Surgical Intensive Care Unit (SICU)   
2          Cardiac Vascular Intensive Care Unit (CVICU)   
3      Medical/Surgical Intensive Care Unit (MICU/SICU)   
4       Neuro Surgical Intensive Care Unit (Neuro SICU)   
...                                                 ...   
76535                Medical Intensive Care Unit (MICU)   
76536  Medical/Surgical Intensive Care Unit (MICU/SICU)   
76537   Neuro Surgical Intensive Care Unit (Neuro SICU)   
76538                Medical Intensive Care Unit (MICU)   
76539                                Neuro Intermediate   

                                          LAST_CAREUNIT               INTIME  \
0          Cardiac Vascular Intensive Care Unit (CVICU)  2110-01-11 10:16:06   
1                   Surgical Intensive Care Unit (SICU)  2110-01-12 00:54:00   
2          Cardiac Vascular Intensive Care Unit (CVICU)  2110-01-13 09:09:40   
3      Medical/Surgical Intensive Care Unit (MICU/SICU)  2110-01-14 07:22:00   
4       Neuro Surgical Intensive Care Unit (Neuro SICU)  2110-01-17 00:28:00   
...                                                 ...                  ...   
76535                Medical Intensive Care Unit (MICU)  2210-11-21 18:42:56   
76536  Medical/Surgical Intensive Care Unit (MICU/SICU)  2211-01-05 10:59:50   
76537   Neuro Surgical Intensive Care Unit (Neuro SICU)  2211-01-14 14:37:00   
76538                Medical Intensive Care Unit (MICU)  2211-05-01 06:59:19   
76539                                Neuro Intermediate  2211-11-09 03:33:00   

                   OUTTIME       LOS            ADMITTIME  \
0      2110-01-12 17:17:47  1.292836  2110-01-11 10:14:00   
1      2110-01-14 22:07:39  2.884479  2110-01-11 22:47:00   
2      2110-01-15 21:45:33  2.524919  2110-01-11 19:58:00   
3      2110-01-15 13:08:36  1.240694  2110-01-14 05:17:00   
4      2110-01-18 01:21:22  1.037060  2110-01-16 23:37:00   
...                    ...       ...                  ...   
76535  2210-11-23 16:03:45  1.889456  2210-11-18 21:47:00   
76536  2211-01-06 17:00:09  1.250220  2211-01-05 10:58:00   
76537  2211-01-17 15:23:45  3.032465  2211-01-14 13:14:00   
76538  2211-05-10 22:51:06  9.660961  2211-05-01 06:57:00   
76539  2211-11-11 18:34:18  2.625903  2211-11-09 02:26:00   

                 DISCHTIME            DEATHTIME     ADMISSION_TYPE  \
0      2110-01-15 17:31:00                  NaN           EW EMER.   
1      2110-01-18 10:25:00                  NaN           EW EMER.   
2      2110-01-17 16:00:00                  NaN             URGENT   
3      2110-01-16 16:34:00                  NaN           EW EMER.   
4      2110-01-22 16:07:00                  NaN           EW EMER.   
...                    ...                  ...                ...   
76535  2210-12-01 17:51:00                  NaN           EW EMER.   
76536  2211-01-07 16:30:00                  NaN       DIRECT EMER.   
76537  2211-01-17 12:34:00  2211-01-17 12:34:00           EW EMER.   
76538  2211-05-12 17:54:00                  NaN           EW EMER.   
76539  2211-11-11 18:15:00                  NaN  OBSERVATION ADMIT   

           ADMISSION_LOCATION            DISCHARGE_LOCATION INSURANCE  \
0                        PACU              HOME HEALTH CARE     Other   
1              EMERGENCY ROOM  CHRONIC/LONG TERM ACUTE CARE     Other   
2      TRANSFER FROM HOSPIT

In [4]:
UNIQUE_IDS =['SUBJECT_ID', 'HADM_ID', 'ICUSTAY_ID']

BINARY_CATEGORIES = ['MORTALITY', 'MORTALITY_INHOSPITAL', 'MORTALITY_INUNIT','TRANSFERBACK',
       'DIEINWARD', 'LESS_THAN_30DAYS', 'DIE_LESS_THAN_30DAYS']    # 'MORTALITY0',

CATEGORIES = [
    'FIRST_CAREUNIT', 'LAST_CAREUNIT',  'ADMISSION_TYPE', 'ADMISSION_LOCATION',
       'DISCHARGE_LOCATION', 'INSURANCE', 'MARITAL_STATUS', 'ETHNICITY', 
        'GENDER']

DATES_CAT = ['INTIME', 'OUTTIME', 'ADMITTIME', 'DISCHTIME', 'DEATHTIME', 'DOB', 'DOD', 'NEXT_INTIME',]

DURATION_CAT = ['DIFF', 'DISCHARGE_DIE', ]

# NUMERIC_CAT =['DAYS_SINCE_LAST_ADMIS', 'NUM_PREV_ADMIS', 'NUM_PREV_PROCS','AGE', 'COUNTS', 'MAX_OUTTIME']
NUMERIC_CAT =['DAYS_SINCE_LAST_ADMIS', 'NUM_PREV_ADMIS', 'NUM_PREV_PROCS','AGE']



MULTIPlE_STR_EMBED = ['PROCEDURES', 'DRUG', 'DIAGS', 'PREV_DIAGS']

LABELS_CAT = ['LOS', 'READMISSION']

MULTIPlE_STR_EMBED_AFTER = ['PROCEDURES_STR', 'DRUG_STR',  'DIAGS_STR', 'PREV_DIAGS_STR']   


In [5]:
# select_features = BINARY_CATEGORIES + CATEGORIES + NUMERIC_CAT + MULTIPlE_STR_EMBED_AFTER
# select_features = CATEGORIES + NUMERIC_CAT + MULTIPlE_STR_EMBED_AFTER
select_features = UNIQUE_IDS + CATEGORIES + NUMERIC_CAT + MULTIPlE_STR_EMBED_AFTER

# select_features = BINARY_CATEGORIES + CATEGORIES + NUMERIC_CAT

In [39]:
# from sklearn.datasets import fetch_openml
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.compose import make_column_selector as selector
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import OrdinalEncoder



catTransformer = Pipeline(steps=[('cat_imputer', SimpleImputer(strategy='constant', fill_value='missing')),('cat_ohe', OneHotEncoder(handle_unknown='ignore'))])

# textTransformer_pr = Pipeline(steps=[('text_bow_1', CountVectorizer())])
# textTransformer_dr = Pipeline(steps=[('text_bow_2', CountVectorizer())])
# textTransformer_di = Pipeline(steps=[('text_bow_3', CountVectorizer())])
# textTransformer_pd = Pipeline(steps=[('text_bow_4', CountVectorizer())])

# catTransformer = Pipeline(steps=[('cat_imputer', SimpleImputer(strategy='constant', fill_value='missing')),('cat_ohe', OrdinalEncoder(encoded_missing_value=-1))])


textTransformer_pr = Pipeline(steps=[('text_bow_1', TfidfVectorizer())])
textTransformer_dr = Pipeline(steps=[('text_bow_2', TfidfVectorizer())])
textTransformer_di = Pipeline(steps=[('text_bow_3', TfidfVectorizer())])
textTransformer_pd = Pipeline(steps=[('text_bow_4', TfidfVectorizer())])


numTransformer = Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),('scaler', StandardScaler())])


In [32]:
# Old way
# from sklearn.model_selection import train_test_split

# X = train_df[select_features].copy()
# # X = train_df[select_features].copy().loc[:10000]
# # columns = X.columns
# # X = pd.DataFrame(X, columns = columns)

# y = train_df['READMISSION']
# # y = train_df['READMISSION'].loc[:10000]




# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state = 42)

train_df_split = train_df_split.loc[train_df_split['READMISSION'] != 2].copy()



# New way
df_train = train_df_split[train_df_split['SUBJECT_LABLE']=='train'].copy()
from sklearn.utils import resample,shuffle

#set the minority class to a seperate dataframe
df_1 = df_train[df_train['READMISSION'] == 1]
#set other classes to another dataframe
other_df = df_train[df_train['READMISSION'] != 1]  
print(df_1.shape)
print(other_df.shape)

#upsample the minority class
df_1_upsampled = resample(df_1,random_state=42,n_samples=len(other_df),replace=True)
print(df_1_upsampled.shape)
# display(df_1_upsampled)
# #concatenate the upsampled dataframe
df_upsampled = pd.concat([df_1_upsampled,other_df])
print(df_upsampled.shape)

df_upsampled.reset_index(drop=True, inplace=True)

df_train = df_upsampled.copy()
display(df_train)

df_test = train_df_split[train_df_split['SUBJECT_LABLE']=='test']



X_train = df_train[select_features].copy()
X_test = df_test[select_features].copy()
y_train = df_train['READMISSION']
y_test = df_test['READMISSION']


from sklearn.utils import shuffle
X_train, y_train, = shuffle(X_train, y_train, random_state=2022)


(10977, 46)
(49634, 46)
(49634, 46)
(99268, 46)


SUBJECT_ID   HADM_ID  ICUSTAY_ID  \
0        15813164  26595460    33211639   
1        13351655  24978460    31230214   
2        12552702  29995331    32982553   
3        18767972  23337651    35458430   
4        16750367  20007871    32764008   
...           ...       ...         ...   
99263    19815165  23465980    31378173   
99264    19437861  23539755    39051902   
99265    18451791  28897092    32688519   
99266    14239401  21199923    35906940   
99267    16703369  27928947    36321770   

                                         FIRST_CAREUNIT  \
0                    Medical Intensive Care Unit (MICU)   
1                   Surgical Intensive Care Unit (SICU)   
2      Medical/Surgical Intensive Care Unit (MICU/SICU)   
3                    Medical Intensive Care Unit (MICU)   
4                              Coronary Care Unit (CCU)   
...                                                 ...   
99263      Cardiac Vascular Intensive Care Unit (CVICU)   
99264                          Coronary Care Unit (CCU)   
99265  Medical/Surgical Intensive Care Unit (MICU/SICU)   
99266                Medical Intensive Care Unit (MICU)   
99267                                Neuro Intermediate   

                                          LAST_CAREUNIT               INTIME  \
0                    Medical Intensive Care Unit (MICU)  2167-08-10 09:15:51   
1                   Surgical Intensive Care Unit (SICU)  2118-12-09 23:54:05   
2      Medical/Surgical Intensive Care Unit (MICU/SICU)  2153-02-01 18:38:25   
3                    Medical Intensive Care Unit (MICU)  2151-09-15 17:48:00   
4                              Coronary Care Unit (CCU)  2155-09-21 17:06:50   
...                                                 ...                  ...   
99263      Cardiac Vascular Intensive Care Unit (CVICU)  2210-04-12 10:50:27   
99264                          Coronary Care Unit (CCU)  2210-06-27 14:39:30   
99265  Medical/Surgical Intensive Care Unit (MICU/SICU)  2211-01-05 10:59:50   
99266                Medical Intensive Care Unit (MICU)  2211-05-01 06:59:19   
99267                                Neuro Intermediate  2211-11-09 03:33:00   

                   OUTTIME        LOS            ADMITTIME  \
0      2167-08-11 16:30:39   1.301944  2167-08-09 22:35:00   
1      2118-12-27 04:51:38  17.206632  2118-12-06 16:05:00   
2      2153-02-02 14:45:01   0.837917  2153-01-18 19:05:00   
3      2151-09-17 12:37:54   1.784653  2151-09-15 16:44:00   
4      2155-09-22 13:43:47   0.858993  2155-09-21 17:06:00   
...                    ...        ...                  ...   
99263  2210-04-19 11:53:49   7.044005  2210-04-12 00:00:00   
99264  2210-06-29 22:23:43   2.322373  2210-06-26 16:00:00   
99265  2211-01-06 17:00:09   1.250220  2211-01-05 10:58:00   
99266  2211-05-10 22:51:06   9.660961  2211-05-01 06:57:00   
99267  2211-11-11 18:34:18   2.625903  2211-11-09 02:26:00   

                 DISCHTIME            DEATHTIME               ADMISSION_TYPE  \
0      2167-08-13 18:29:00                  NaN                     EW EMER.   
1      2118-12-27 23:47:00  2118-12-27 23:47:00                       URGENT   
2      2153-02-28 17:21:00                  NaN                       URGENT   
3      2151-09-21 20:15:00                  NaN                     EW EMER.   
4      2155-10-01 14:45:00                  NaN                 DIRECT EMER.   
...                    ...                  ...                          ...   
99263  2210-05-25 17:31:00                  NaN  SURGICAL SAME DAY ADMISSION   
99264  2210-06-30 17:30:00                  NaN            OBSERVATION ADMIT   
99265  2211-01-07 16:30:00                  NaN                 DIRECT EMER.   
99266  2211-05-12 17:54:00                  NaN                     EW EMER.   
99267  2211-11-11 18:15:00                  NaN            OBSERVATION ADMIT   

           ADMISSION_LOCATION            DISCHARGE_LOCATION INSURANCE  \
0              EMERGENCY ROOM            

In [33]:
print(X_train.shape)
X_train.head()

(99268, 20)


SUBJECT_ID   HADM_ID  ICUSTAY_ID                       FIRST_CAREUNIT  \
53842    18589606  25741706    39369416                  Trauma SICU (TSICU)   
51077    14367016  24607380    35030433             Coronary Care Unit (CCU)   
35049    12672587  29401070    37868786             Coronary Care Unit (CCU)   
1771     19545704  24036958    31735593   Medical Intensive Care Unit (MICU)   
74964    16905190  20590079    30781094  Surgical Intensive Care Unit (SICU)   

                             LAST_CAREUNIT               ADMISSION_TYPE  \
53842                  Trauma SICU (TSICU)  SURGICAL SAME DAY ADMISSION   
51077             Coronary Care Unit (CCU)                 DIRECT EMER.   
35049             Coronary Care Unit (CCU)  SURGICAL SAME DAY ADMISSION   
1771    Medical Intensive Care Unit (MICU)                     EW EMER.   
74964  Surgical Intensive Care Unit (SICU)                     EW EMER.   

          ADMISSION_LOCATION        DISCHARGE_LOCATION INSURANCE  \
53842     PHYSICIAN REFERRAL                      HOME  Medicare   
51077     PHYSICIAN REFERRAL  SKILLED NURSING FACILITY     Other   
35049     PHYSICIAN REFERRAL  SKILLED NURSING FACILITY     Other   
1771          EMERGENCY ROOM                     REHAB  Medicare   
74964  WALK-IN/SELF REFERRAL                      HOME     Other   

      MARITAL_STATUS               ETHNICITY GENDER  DAYS_SINCE_LAST_ADMIS  \
53842        WIDOWED                   WHITE      F               5.708333   
51077         SINGLE                   WHITE      F              31.125000   
35049        MARRIED                   OTHER      F               0.000000   
1771          SINGLE                   WHITE      M             809.426389   
74964        MARRIED  BLACK/AFRICAN AMERICAN      F               0.000000   

       NUM_PREV_ADMIS  NUM_PREV_PROCS  AGE  \
53842             1.0             2.0   90   
51077             1.0             0.0   90   
35049             0.0             0.0   90   
1771              3.0            29.0    2   
74964             0.0             0.0    3   

                                          PROCEDURES_STR  \
53842  Intraspinal abscess Regional lymph node excisi...   
51077  Measurement of Cardiac Sampling and Pressure, ...   
35049  Destruction of Ventricular Septum, Percutaneou...   
1771   Refusion of dorsal and dorsolumbar spine, post...   
74964  Control Bleeding in Gastrointestinal Tract, Vi...   

                                                DRUG_STR  \
53842  0.9% Sodium Chloride, Potassium Chloride, Hepa...   
51077  Influenza Vaccine Quadrivalent, PNEUMOcoccal 2...   
35049  Sterile Water, Influenza Vaccine Quadrivalent,...   
1771   Sodium Chloride 0.9%  Flush, Pantoprazole, Cef...   
74964  Heparin, Potassium Chloride Replacement (Criti...   

                                               DIAGS_STR  \
53842  Malignant neoplasm of upper lobe, bronchus or ...   
51077  Non-ST elevation (NSTEMI) myocardial infarctio...   
35049  Stenosis of other cardiac prosthetic devices, ...   
1771   Secondary malignant neoplasm of bone and bone ...   
74964  Postprocedural hemorrhage of a digestive syste...   

                                          PREV_DIAGS_STR  
53842  Other diseases of lung, not elsewhere classifi...  
51077  Collapsed vertebra, not elsewhere classified, ...  
35049                                            Unknown  
1771   Secondary malignant neoplasm of bone and bone ...  
74964                                            Unknown

In [34]:
print(y_train.shape)
y_train.head()

(99268,)


53842    0
51077    0
35049    1
1771     1
74964    0
Name: READMISSION, dtype: int64

## FastText encoding

In [11]:
from gensim.models import FastText
import numpy as np
# from gensim.models import Word2Vec
from scipy.spatial.distance import cosine as cos_dist

class FastTextEmbedModelWrapper(object):

    def __init__(self, min_count, vector_size, iterations, window):
        self.w2v_model = None
        self.min_count = min_count
        self.vector_size = vector_size
        self.iterations = iterations
        self.window = window

    def train(self, tokenized_abstracts):
        # @param tokenized_abstracts - a list of lists of strings
        # Based on this: https://towardsdatascience.com/a-beginners-guide-to-word-embedding-with-gensim-word2vec-model-5970fa56cc92
        print("training model")
        self.w2v_model = FastText(
            tokenized_abstracts, min_count=self.min_count, vector_size=self.vector_size,
            workers=3, window=self.window, sg=0, epochs=self.iterations)

    def save(self, filename):
        # save both models
        self.w2v_model.save(filename + "_ft")


    def load(self, filename):
        # load both models
        self.w2v_model = FastText.load(filename + "_ft")
        
    def similarity(self, w1, w2):
        return self.w2v_model.wv.similarity(w1, w2)

    def get_vocab(self):
        return self.w2v_model.wv.key_to_index

    def get_vocab_list(self):
        return list(self.w2v_model.wv.key_to_index.keys())

    def get_count(self, w):
        if w in self.w2v_model.wv.key_to_index:
            return self.w2v_model.wv.key_to_index[w].count
        return 0

    def most_similar(self, word, topn=5):
        top = []
        # Or use w2v
        if word in self.w2v_model.wv.key_to_index:
            top = self.w2v_model.wv.most_similar(positive=word, topn=topn)
        return top

    def get_word_vectors_as_matrix_rows(self, index_to_word):
        """index_to_word - a list of words in the required order"""
        vectors = []
        for w in index_to_word:
            vectors.append(self.w2v_model.wv[w])
        return np.array(vectors)

    def export_embeddings(self, output_file):
        """model is an instance of EmbedModelWrapper"""
        vocab = self.get_vocab_list()
        matrix = self.get_word_vectors_as_matrix_rows(vocab)
        out = open(output_file, "w")
        for i in range(len(vocab)):
            vector_as_str = ",".join([str(x) for x in matrix[i]])
            out.write("{}\t{}\n".format(vocab[i], vector_as_str))

In [12]:
READ_MODELS = True
SAVE_MODELS = True

ONLY_CONCEPTS = False
MODE = "plain_text"  # 'plain_text', 'cui2vec_style' or 'only_concepts'
MIN_COUNT = 0
MIN_COUNT_BEFORE_REP = 0 # 40
VECTOR_SIZE = 100  # 50, 70, 100, 300
TRAINING_ITERATIONS = 20  # 35
WINDOW = 20 # 20
TOPN = 10

In [13]:
race_sensitive_model_file_template = "embedding_models/race-sensitive{}.model"
neutral_model_file_template = "embedding_models/neutral{}.model"


iterations = ['_plain_text_FT_vec100_win20_ti20']
neutral_ft, race_sensitive_ft = [], []
for iteration in iterations:
    race_sensitive_model_file_ft = race_sensitive_model_file_template.format(iteration)
    neutral_model_file_ft = neutral_model_file_template.format(iteration)

    race_sensitive_ft = FastTextEmbedModelWrapper(min_count=MIN_COUNT,
                           vector_size=VECTOR_SIZE, iterations=TRAINING_ITERATIONS,
                           window=WINDOW)
    neutral_ft = FastTextEmbedModelWrapper(min_count=MIN_COUNT,
                                vector_size=VECTOR_SIZE, iterations=TRAINING_ITERATIONS,
                                window=WINDOW)

if READ_MODELS:
    race_sensitive_ft.load(race_sensitive_model_file_ft)
    neutral_ft.load(neutral_model_file_ft)


In [14]:
import nltk
from nltk.tokenize import word_tokenize
from nltk import sent_tokenize
from nltk import pos_tag
from nltk.corpus import stopwords

from nltk.stem.snowball import SnowballStemmer
from nltk.stem import WordNetLemmatizer

from nltk.corpus import wordnet
import re
import string


def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    if treebank_tag.startswith('V'):
        return wordnet.VERB
    if treebank_tag.startswith('N'):
        return wordnet.NOUN
    if treebank_tag.startswith('R'):
        return wordnet.ADV
    return wordnet.NOUN

def is_english_word(word_to_check):
    return len(wordnet.synsets(word_to_check)) > 0


def represents_number(word_to_check):
    possible_numbers = re.findall(r'[\d\.]+', word_to_check)
    if len(possible_numbers) > 0 and len(possible_numbers[0]) == len(word_to_check):
        return True
    syns = wordnet.synsets(word_to_check)
    for s in syns:
        if s.definition().startswith("the cardinal number"):
            return True
    if "-" in word_to_check:
        word = word_to_check.split("-")[0]
        syns = wordnet.synsets(word)
        for s in syns:
            if s.definition().startswith("the cardinal number"):
                return True
    return False


def clean(text):
    """tokenize, remove stop words and numbers, and lemmatize."""
    stop_words = stopwords.words('english')

    lemmatizer = WordNetLemmatizer()
    tokens = word_tokenize(text)
    pos = pos_tag(tokens)
    lemm = [lemmatizer.lemmatize(word, pos=get_wordnet_pos(p)).lower() for word, p in pos]
    without_stop_words = [word for word in lemm
                          if word not in stop_words
                          and word not in string.punctuation
                          and not represents_number(word)
                          and is_english_word(word)]
    return without_stop_words


print(clean('Type 2 diabetes'))


# def get_embedding_sent_ft(ft_model, text):
#     '''
#     Uses the provided model and tokenizer to produce an embedding for the
#     provided `text`, and a "contextualized" embedding for `word`, if provided.
#     '''
#     return ft_model.w2v_model.wv[text].tolist()


def get_embedding_sent_ft(ft_model, text):
    '''
    Uses the provided model and tokenizer to produce an embedding for the
    provided `text`, and a "contextualized" embedding for `word`, if provided.
    '''
    c_text = clean(text)
    voc = ft_model.w2v_model.wv
    results = []
    for c in c_text:
        if c in voc:
            results.append(voc[c])
    if len(results)>0:
        return np.mean(results, axis=0).tolist()
    else:
        return voc['unknown'].tolist()
    

text1= 'Type 2 diabetes'
print(get_embedding_sent_ft(race_sensitive_ft, text1))
print(get_embedding_sent_ft(race_sensitive_ft, text1))
# get_embedding_sent_ft(wm_ft, 'unknown')

['type', 'diabetes']
[-3.306001663208008, 4.189043998718262, -8.08740234375, 0.864585816860199, 1.1535636186599731, -3.648409366607666, 0.7023245692253113, -1.7919292449951172, -4.889386177062988, 7.663961410522461, 3.424579381942749, 0.9388614892959595, -0.02266693115234375, -2.476900577545166, 3.125725746154785, -0.780820369720459, 0.8294589519500732, 1.6297342777252197, 0.013943195343017578, 1.6224150657653809, 1.2995021343231201, -6.081752300262451, -3.966399908065796, -0.3505142331123352, -1.9755496978759766, -5.399570941925049, 7.869070053100586, -5.594446182250977, 4.704102039337158, -3.4209136962890625, 2.155932903289795, 4.098267555236816, -7.010969161987305, 9.259488105773926, 6.185752868652344, -7.113613128662109, -4.848451614379883, -2.992143154144287, 2.0768215656280518, -2.3486766815185547, 4.347374439239502, -4.865492343902588, 7.272765159606934, -0.4214570224285126, -3.6048543453216553, 1.6199321746826172, -2.7006635665893555, -0.8770607113838196, 0.7817324995994568, 2.

In [15]:
text1= 'Type 2 diabetes'
print(get_embedding_sent_ft(race_sensitive_ft, text1))

print(get_embedding_sent_ft(neutral_ft, text1))
type(get_embedding_sent_ft(neutral_ft, text1))

[-3.306001663208008, 4.189043998718262, -8.08740234375, 0.864585816860199, 1.1535636186599731, -3.648409366607666, 0.7023245692253113, -1.7919292449951172, -4.889386177062988, 7.663961410522461, 3.424579381942749, 0.9388614892959595, -0.02266693115234375, -2.476900577545166, 3.125725746154785, -0.780820369720459, 0.8294589519500732, 1.6297342777252197, 0.013943195343017578, 1.6224150657653809, 1.2995021343231201, -6.081752300262451, -3.966399908065796, -0.3505142331123352, -1.9755496978759766, -5.399570941925049, 7.869070053100586, -5.594446182250977, 4.704102039337158, -3.4209136962890625, 2.155932903289795, 4.098267555236816, -7.010969161987305, 9.259488105773926, 6.185752868652344, -7.113613128662109, -4.848451614379883, -2.992143154144287, 2.0768215656280518, -2.3486766815185547, 4.347374439239502, -4.865492343902588, 7.272765159606934, -0.4214570224285126, -3.6048543453216553, 1.6199321746826172, -2.7006635665893555, -0.8770607113838196, 0.7817324995994568, 2.973907470703125, -6.8

list

In [16]:
import time
from tqdm.auto import tqdm
from sklearn.base import BaseEstimator, TransformerMixin

tqdm.pandas()

class EncodeColumns(BaseEstimator, TransformerMixin):
    def __init__(self, model=None):
        self.model = model
    
    def fit(self, X, y=None):
        return self

    def transform(self, X, y=None):
        cols_to_transform = list(X.columns)

#         if self.columns:
#             cols_to_transform = self.columns
        
        for col_to_transform in cols_to_transform:
#             X[col_to_transform] = X.apply(lambda x: get_embedding_sent(self.model, self.tokenizer, x[col_to_transform]), axis=1)
#             X[col_to_transform] = X[col_to_transform].apply(lambda x: get_embedding_sent(self.model, self.tokenizer, x))
#             X[col_to_transform] = X[col_to_transform].progress_apply(lambda x: get_embedding_sent(self.model, self.tokenizer, x))       
            text_list = X[col_to_transform].tolist()
            embed_list = []
            for text in tqdm(text_list, position=0, leave=True):
                sen_emb = get_embedding_sent_ft(self.model, text)
                embed_list.append(sen_emb)
            assert len(text_list) == len(embed_list)
            X[col_to_transform] = np.array(embed_list)
        return X


/home/hl2659/miniconda3/envs/hao_ner/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [17]:
NUMERIC_CAT

['DAYS_SINCE_LAST_ADMIS', 'NUM_PREV_ADMIS', 'NUM_PREV_PROCS', 'AGE']

### race_sensitive_ft model result

In [44]:
textTransformer_pr_encode = Pipeline(steps=[('encode_cols', EncodeColumns(model=race_sensitive_ft,))])


# New way - encode procedures, diag, and prev diag
ct = ColumnTransformer(
transformers=[
('cat', catTransformer, CATEGORIES),  # BINARY_CATEGORIES + CATEGORIES
('num', numTransformer, NUMERIC_CAT),
# ('text1', textTransformer_pr, 'PROCEDURES_STR'),
('text1', textTransformer_pr_encode, ['PROCEDURES_STR','DIAGS_STR','PREV_DIAGS_STR']),
('text2', textTransformer_dr, 'DRUG_STR'),
# ('text3', textTransformer_di, 'DIAGS_STR'),
# ('text4', textTransformer_pd, 'PREV_DIAGS_STR'),
])  #, n_jobs=8 will fail  # , remainder='passthrough' no need, default 'drop' fine

In [46]:
from tqdm.auto import tqdm

from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression

classifiers = [
    KNeighborsClassifier(10),
    #     SVC(kernel="linear", C=0.025),  # , verbose=True   # slow and not scalable 
    LinearSVC(random_state=0, tol=1e-5),
#     SVC(gamma='auto', C=1, max_iter=1000),   # , verbose=True # slow and not scalable 
    DecisionTreeClassifier(max_depth=10),
    RandomForestClassifier(max_depth=10, n_estimators=10, n_jobs=-1, class_weight='balanced'),  # , verbose=True
    MLPClassifier(alpha=1, max_iter=1000, early_stopping=True),  # , verbose=True
    AdaBoostClassifier(),
    LogisticRegression(C=10, max_iter=1000,)
]

trainX = ct.fit_transform(X_train)
print(trainX.shape)

testX = ct.transform(X_test)
print(testX.shape)

for item in tqdm(classifiers):
    print('**********'*10)
    print(item)
    clf = item

    clf.fit(trainX, y_train)

    preds = clf.predict(testX)

    print('accuracy %s' % accuracy_score(preds, y_test))
    print(confusion_matrix(y_test, preds))
    print(classification_report(y_test, preds, digits=4))

100%|██████████| 99268/99268 [1:05:50<00:00, 25.13it/s]


(99268, 3148)


100%|██████████| 10660/10660 [05:09<00:00, 34.39it/s]


(10660, 3148)


  0%|          | 0/7 [00:00<?, ?it/s]

****************************************************************************************************
KNeighborsClassifier(n_neighbors=10)


 14%|█▍        | 1/7 [02:46<16:36, 166.12s/it]

accuracy 0.6754221388367729
[[6156 2541]
 [ 919 1044]]
              precision    recall  f1-score   support

           0     0.8701    0.7078    0.7806      8697
           1     0.2912    0.5318    0.3764      1963

    accuracy                         0.6754     10660
   macro avg     0.5807    0.6198    0.5785     10660
weighted avg     0.7635    0.6754    0.7062     10660

****************************************************************************************************
LinearSVC(random_state=0, tol=1e-05)


/home/hl2659/miniconda3/envs/hao_ner/lib/python3.9/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
 29%|██▊       | 2/7 [04:00<09:19, 111.98s/it]

accuracy 0.7546904315196998
[[6784 1913]
 [ 702 1261]]
              precision    recall  f1-score   support

           0     0.9062    0.7800    0.8384      8697
           1     0.3973    0.6424    0.4909      1963

    accuracy                         0.7547     10660
   macro avg     0.6518    0.7112    0.6647     10660
weighted avg     0.8125    0.7547    0.7744     10660

****************************************************************************************************
DecisionTreeClassifier(max_depth=10)


 43%|████▎     | 3/7 [04:21<04:41, 70.48s/it] 

accuracy 0.7194183864915572
[[6434 2263]
 [ 728 1235]]
              precision    recall  f1-score   support

           0     0.8984    0.7398    0.8114      8697
           1     0.3531    0.6291    0.4523      1963

    accuracy                         0.7194     10660
   macro avg     0.6257    0.6845    0.6318     10660
weighted avg     0.7979    0.7194    0.7453     10660

****************************************************************************************************
RandomForestClassifier(class_weight='balanced', max_depth=10, n_estimators=10,
                       n_jobs=-1)


 57%|█████▋    | 4/7 [04:22<02:09, 43.01s/it]

accuracy 0.7413696060037523
[[6683 2014]
 [ 743 1220]]
              precision    recall  f1-score   support

           0     0.8999    0.7684    0.8290      8697
           1     0.3772    0.6215    0.4695      1963

    accuracy                         0.7414     10660
   macro avg     0.6386    0.6950    0.6493     10660
weighted avg     0.8037    0.7414    0.7628     10660

****************************************************************************************************
MLPClassifier(alpha=1, early_stopping=True, max_iter=1000)


 71%|███████▏  | 5/7 [08:49<04:07, 123.91s/it]

accuracy 0.7682926829268293
[[6994 1703]
 [ 767 1196]]
              precision    recall  f1-score   support

           0     0.9012    0.8042    0.8499      8697
           1     0.4126    0.6093    0.4920      1963

    accuracy                         0.7683     10660
   macro avg     0.6569    0.7067    0.6709     10660
weighted avg     0.8112    0.7683    0.7840     10660

****************************************************************************************************
AdaBoostClassifier()


 86%|████████▌ | 6/7 [09:57<01:44, 104.87s/it]

accuracy 0.7701688555347092
[[6963 1734]
 [ 716 1247]]
              precision    recall  f1-score   support

           0     0.9068    0.8006    0.8504      8697
           1     0.4183    0.6353    0.5044      1963

    accuracy                         0.7702     10660
   macro avg     0.6625    0.7179    0.6774     10660
weighted avg     0.8168    0.7702    0.7867     10660

****************************************************************************************************
LogisticRegression(C=10, max_iter=1000)


/home/hl2659/miniconda3/envs/hao_ner/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
100%|██████████| 7/7 [11:15<00:00, 96.53s/it] 

accuracy 0.7535647279549719
[[6760 1937]
 [ 690 1273]]
              precision    recall  f1-score   support

           0     0.9074    0.7773    0.8373      8697
           1     0.3966    0.6485    0.4922      1963

    accuracy                         0.7536     10660
   macro avg     0.6520    0.7129    0.6647     10660
weighted avg     0.8133    0.7536    0.7738     10660



In [ ]:
# Old way 
# for item in tqdm(classifiers):
#     print('**********'*10)
#     print(item)
#     clf = item
#     pipeline = Pipeline(steps=[('feature_engineer', ct),
#                                ('clf', clf)])

#     pipeline.fit(X_train, y_train)

#     preds = pipeline.predict(X_test)

#     print('accuracy %s' % accuracy_score(preds, y_test))
#     print(confusion_matrix(y_test, preds))
#     print(classification_report(y_test, preds, digits=4))
    
    

In [ ]:
## require dense matrix

# from sklearn.preprocessing import FunctionTransformer

# classifiers2 = [ 
#                 GaussianNB(),
#                 QuadraticDiscriminantAnalysis(),
# #                 GaussianProcessClassifier(1.0 * RBF(1.0), n_jobs=1),  # slow and fail
#                ]
# for item in tqdm(classifiers2):
#     print('**********'*10)
#     print(item)
#     clf = item
#     pipeline = Pipeline(steps=[('feature_engineer', ct),
#                                ('sparse_to_dense', FunctionTransformer(lambda x: x.todense(), accept_sparse=True)), 
#                                ('clf', clf)])

#     pipeline.fit(X_train, y_train)

#     preds = pipeline.predict(X_test)

#     print('accuracy %s' % accuracy_score(preds, y_test))
#     print(confusion_matrix(y_test, preds))
#     print(classification_report(y_test, preds, digits=4))

### neutral model result

In [47]:
textTransformer_pr_encode = Pipeline(steps=[('encode_cols', EncodeColumns(model=neutral_ft,))])


# New way - encode procedures, diag, and prev diag
ct = ColumnTransformer(
transformers=[
('cat', catTransformer, CATEGORIES),  # BINARY_CATEGORIES + CATEGORIES
('num', numTransformer, NUMERIC_CAT),
# ('text1', textTransformer_pr, 'PROCEDURES_STR'),
('text1', textTransformer_pr_encode, ['PROCEDURES_STR','DIAGS_STR','PREV_DIAGS_STR']),
('text2', textTransformer_dr, 'DRUG_STR'),
# ('text3', textTransformer_di, 'DIAGS_STR'),
# ('text4', textTransformer_pd, 'PREV_DIAGS_STR'),
])  #, n_jobs=8 will fail  # , remainder='passthrough' no need, default 'drop' fine

In [48]:
from tqdm.auto import tqdm

from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression

classifiers = [
    KNeighborsClassifier(10),
    #     SVC(kernel="linear", C=0.025),  # , verbose=True   # slow and not scalable 
    LinearSVC(random_state=0, tol=1e-5),
#     SVC(gamma='auto', C=1, max_iter=1000),   # , verbose=True # slow and not scalable 
    DecisionTreeClassifier(max_depth=10),
    RandomForestClassifier(max_depth=10, n_estimators=10, n_jobs=-1, class_weight='balanced'),  # , verbose=True
    MLPClassifier(alpha=1, max_iter=1000, early_stopping=True),  # , verbose=True
    AdaBoostClassifier(),
    LogisticRegression(C=10, max_iter=1000,)
]

trainX = ct.fit_transform(X_train)
print(trainX.shape)

testX = ct.transform(X_test)
print(testX.shape)

for item in tqdm(classifiers):
    print('**********'*10)
    print(item)
    clf = item

    clf.fit(trainX, y_train)

    preds = clf.predict(testX)

    print('accuracy %s' % accuracy_score(preds, y_test))
    print(confusion_matrix(y_test, preds))
    print(classification_report(y_test, preds, digits=4))


    

100%|██████████| 99268/99268 [41:36<00:00, 39.76it/s]  


(99268, 3148)


100%|██████████| 10660/10660 [03:05<00:00, 57.52it/s]


(10660, 3148)


  0%|          | 0/7 [00:00<?, ?it/s]

****************************************************************************************************
KNeighborsClassifier(n_neighbors=10)


 14%|█▍        | 1/7 [02:28<14:48, 148.07s/it]

accuracy 0.676172607879925
[[6142 2555]
 [ 897 1066]]
              precision    recall  f1-score   support

           0     0.8726    0.7062    0.7806      8697
           1     0.2944    0.5430    0.3818      1963

    accuracy                         0.6762     10660
   macro avg     0.5835    0.6246    0.5812     10660
weighted avg     0.7661    0.6762    0.7072     10660

****************************************************************************************************
LinearSVC(random_state=0, tol=1e-05)


/home/hl2659/miniconda3/envs/hao_ner/lib/python3.9/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
 29%|██▊       | 2/7 [03:33<08:16, 99.20s/it] 

accuracy 0.7567542213883677
[[6812 1885]
 [ 708 1255]]
              precision    recall  f1-score   support

           0     0.9059    0.7833    0.8401      8697
           1     0.3997    0.6393    0.4919      1963

    accuracy                         0.7568     10660
   macro avg     0.6528    0.7113    0.6660     10660
weighted avg     0.8126    0.7568    0.7760     10660

****************************************************************************************************
DecisionTreeClassifier(max_depth=10)


 43%|████▎     | 3/7 [03:52<04:10, 62.71s/it]

accuracy 0.7236397748592871
[[6483 2214]
 [ 732 1231]]
              precision    recall  f1-score   support

           0     0.8985    0.7454    0.8149      8697
           1     0.3573    0.6271    0.4553      1963

    accuracy                         0.7236     10660
   macro avg     0.6279    0.6863    0.6351     10660
weighted avg     0.7989    0.7236    0.7486     10660

****************************************************************************************************
RandomForestClassifier(class_weight='balanced', max_depth=10, n_estimators=10,
                       n_jobs=-1)


 57%|█████▋    | 4/7 [03:53<01:54, 38.31s/it]

accuracy 0.7569418386491558
[[6857 1840]
 [ 751 1212]]
              precision    recall  f1-score   support

           0     0.9013    0.7884    0.8411      8697
           1     0.3971    0.6174    0.4833      1963

    accuracy                         0.7569     10660
   macro avg     0.6492    0.7029    0.6622     10660
weighted avg     0.8084    0.7569    0.7752     10660

****************************************************************************************************
MLPClassifier(alpha=1, early_stopping=True, max_iter=1000)


 71%|███████▏  | 5/7 [07:12<03:12, 96.39s/it]

accuracy 0.7329268292682927
[[6511 2186]
 [ 661 1302]]
              precision    recall  f1-score   support

           0     0.9078    0.7486    0.8206      8697
           1     0.3733    0.6633    0.4777      1963

    accuracy                         0.7329     10660
   macro avg     0.6406    0.7060    0.6492     10660
weighted avg     0.8094    0.7329    0.7575     10660

****************************************************************************************************
AdaBoostClassifier()


 86%|████████▌ | 6/7 [08:11<01:23, 83.74s/it]

accuracy 0.7701688555347092
[[6963 1734]
 [ 716 1247]]
              precision    recall  f1-score   support

           0     0.9068    0.8006    0.8504      8697
           1     0.4183    0.6353    0.5044      1963

    accuracy                         0.7702     10660
   macro avg     0.6625    0.7179    0.6774     10660
weighted avg     0.8168    0.7702    0.7867     10660

****************************************************************************************************
LogisticRegression(C=10, max_iter=1000)


/home/hl2659/miniconda3/envs/hao_ner/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
100%|██████████| 7/7 [08:44<00:00, 75.00s/it]

accuracy 0.7553470919324577
[[6781 1916]
 [ 692 1271]]
              precision    recall  f1-score   support

           0     0.9074    0.7797    0.8387      8697
           1     0.3988    0.6475    0.4936      1963

    accuracy                         0.7553     10660
   macro avg     0.6531    0.7136    0.6662     10660
weighted avg     0.8137    0.7553    0.7752     10660



In [49]:
clf.__class__.__name__

'LogisticRegression'

In [53]:
from sklearn.metrics import roc_auc_score


roc_auc_score(y_test, clf.predict_proba(testX)[:, 1])

# roc_auc_score(y_test, clf.decision_function(testX))





0.7836034535889932

In [ ]:
# for item in tqdm(classifiers):
#     print('**********'*10)
#     print(item)
#     clf = item
#     pipeline = Pipeline(steps=[('feature_engineer', ct),
#                                ('clf', clf)])

#     pipeline.fit(X_train, y_train)

#     preds = pipeline.predict(X_test)

#     print('accuracy %s' % accuracy_score(preds, y_test))
#     print(confusion_matrix(y_test, preds))
#     print(classification_report(y_test, preds, digits=4))

In [ ]:
Extra

In [107]:

import pandas as pd
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder
from sklearn.feature_extraction.text import TfidfVectorizer


textTransformer_pr = Pipeline(steps=[('text_bow_1', TfidfVectorizer())])
textTransformer_dr = Pipeline(steps=[('text_bow_2', TfidfVectorizer())])
textTransformer_di = Pipeline(steps=[('text_bow_3', TfidfVectorizer())])
textTransformer_pd = Pipeline(steps=[('text_bow_4', TfidfVectorizer())])




df = pd.DataFrame({"a": ['green', 'red', 'yellow'], "b": [-4, 5, 6], "c": [-7, -8, 9], "d": ['test rock', 'rock stone', 'stone river']})

print(df)
numTransformer = Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),('scaler', StandardScaler())])
# numTransformer = Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),('scaler', MinMaxScaler())])
# numTransformer = Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),('scaler', QuantileTransformer(n_quantiles=10, random_state=0))])
# catTransformer = Pipeline(steps=[('cat_imputer', SimpleImputer(strategy='constant', fill_value='missing')),('cat_ohe', OneHotEncoder(handle_unknown='ignore'))])
catTransformer = Pipeline(steps=[('cat_imputer', SimpleImputer(strategy='constant', fill_value='missing')),('cat_ohe', OrdinalEncoder(encoded_missing_value=-1))])


from sklearn.feature_extraction import FeatureHasher
h = FeatureHasher(n_features=10)


ct = ColumnTransformer(
transformers=[
('cat', catTransformer, ['a']),  # BINARY_CATEGORIES + CATEGORIES
('num', numTransformer, ['b', 'c']),
('text1', textTransformer_pr, 'd'),
])

transformed_df =ct.fit_transform(df)
print(transformed_df)


ct = ColumnTransformer(
transformers=[
('cat', catTransformer, ['a']),  # BINARY_CATEGORIES + CATEGORIES
('num', numTransformer, ['b', 'c']),
('text1', textTransformer_pr_encode, ['d']),
])

transformed_df =ct.fit_transform(df)
print(transformed_df)

        a  b  c            d
0   green -4 -7    test rock
1     red  5 -8   rock stone
2  yellow  6  9  stone river
[[ 0.         -1.4083737  -0.64194074  0.          0.60534851  0.
   0.79596054]
 [ 1.          0.59299945 -0.77032889  0.          0.70710678  0.70710678
   0.        ]
 [ 2.          0.81537425  1.41226963  0.79596054  0.          0.60534851
   0.        ]]


100%|██████████| 3/3 [00:00<00:00, 419.60it/s]

[[ 0.         -1.4083737  -0.64194074 -0.24966379  2.33561254 -5.96262503
  -2.68934178 -2.92044616 -1.42373407 -1.14662814 -2.63433075  2.82056713
  -1.82907057 -1.35659027  0.20034319 -2.56096649 -7.15845823  2.56776619
   1.2456423   2.49276853  6.51537895 -4.68979836  2.38200188 -0.62866324
  -4.85660553  2.09000802 -1.07039797  6.41304922  5.64254475  1.59915376
  -3.5200789  -2.36704326 -0.59246612  3.48685741 -0.59312493 -0.87151164
   6.76574612 -2.53177929 -0.68154961 -1.35057282 -3.95582843  1.42547321
  -2.18339992]
 [ 1.          0.59299945 -0.77032889 -0.25866443  1.97003865 -2.11513567
   2.87909985  0.96808255 -2.06404018  0.88643175  0.05082509 -0.42252266
  -2.05527472 -2.06831145 -1.83205557  4.5681076  -0.89004779  0.16115353
   0.41622177  0.10458159  2.00652432 -3.69669986  2.85240841 -0.49943644
  -0.43540499  1.64684176 -0.39426214  2.58986902  4.2359004   2.50406003
  -2.15363526 -2.00755191  0.28758013 -0.28965825 -3.22096276 -2.22820401
   0.98841918 -3.164906